### ISSUE TITLE
Provide support for .tsx files

### ISSUE THREAD

**Issue by enoh-barbu** [Gelio/tslint-react-hooks#15]
I'm using create-react-app with typescript, I have installed the tsling plugin and made all related stuff but it doesn't work with .tsx files. 
If I change the file name to .ts it will identify the errors though.

**Comment by Gelio** [comment]
Do other rules work in *.tsx files 🙂?

This rule does not have any hardcoded limitation to handle only *.ts files. It may be a configuration problem in your case, that *.tsx files are not linted at all.

**Comment by enoh-barbu** [comment]
I did zero configuration for my demo project as I just used the command line to generate the project by using create-react-app with typescript flag, and after just installing the linting. I will try again with a fresh new project using the same approach.

**Comment by Gelio** [comment]
Were you able to reproduce the issue 🙂 ?

**Comment by enoh-barbu** [comment]
Hey, 10x for the reminder, I forgot about it, so I just did a fresh installation but same result. I think it might be also related to my editor. Let's just close this for now and if there will be more people complaining about the same issue, we might discuss further.
