### ISSUE TITLE
Detect use of useState inside useEffect

### ISSUE THREAD

**Issue by linonetwo** [Gelio/tslint-react-hooks#16]
This will cause lots of rerender, without warning.

**Comment by Gelio** [comment]
Thanks for posting an issue 🙂 

Are you sure that `useState` inside `useEffect` does not result in any violations? For me, the following snippet:

```ts
function MyComponent() {
  React.useEffect(() => {
    React.useState(() => {

    })
  })
}
```

results in a rightful rule violation:

![image](https://user-images.githubusercontent.com/889383/56382763-74cf7180-6218-11e9-90bc-cf9cab6b8b91.png)

Could you share a snippet of this case that does not result in a rule violation? 🙂

**Comment by linonetwo** [comment]
Hi, I just found that, in some case likes:

```js
  const [currentRenderCounter, setRenderCounter] = useState(0);
  useEffect(() => {
    if (shouldRender) {
      setRenderCounter(counter => counter + 1);
      console.log(currentRenderCounter);
...
```
Will cause infinite loop of rendering.

But in some case, it's fine to use state in `useEffect`... I'm still confise why some times it works.

The safe way is to useRef:

```js
  const renderCounter = useRef(0);

  useEffect(() => {
    if (shouldRender) {
      renderCounter.current += 1;
      console.log(renderCounter.current);
...
```

**Comment by Gelio** [comment]
I am not convinced that this is a responsibility of the linter to report such behavior 🙂 Statically analyzing the code would not result in enough information to determine that `setCounterRender` will cause an endless loop.

Moreover, in some cases, the code snippet you provided is the wanted behavior, as in some cases `shouldRender` may be falsy. That is why it would not be easy to stop such behavior even during runtime.

All in all, I have no easy idea on how to implement such verification, therefore I am closing this issue. If you, or anyone else, has an implementation idea, feel free to create a PR 🙂
