### ISSUE TITLE
Confused with rules

### ISSUE THREAD

**Issue by BenevidesLecontes** [Gelio/tslint-react-hooks#18]
Hi, thank you for your work. I'm confused with some rules.
My IDE report errors for some files and not on others, I have the same idea in two files, in the first file i don't have any errors, but in the second i have errors. My code is wrong or not?
<img width="1049" alt="Screen Shot 2019-04-24 at 11 50 42" src="https://user-images.githubusercontent.com/1839361/56669527-abc5dd00-6687-11e9-8be3-76ce4bcdaa29.png">
<img width="1331" alt="Screen Shot 2019-04-24 at 11 49 59" src="https://user-images.githubusercontent.com/1839361/56669528-ac5e7380-6687-11e9-8364-e4ee9d24f8d4.png">

**Comment by Gelio** [comment]
Hooks can only be used inside function components and custom hooks. There are 2 heuristics in place for detecting those entities:

1. If a function starts with a capital letter (as components are usually named, e.g. `MyComponent`) then the rule assumes that the function is a function component.
2. If a function starts with `use` and then a capital letter (as custom hooks are usually named and as the React team suggests to name custom hooks, e.g. `useCustomHook`) then the rule assumes that the function is a custom hook.

If those two rules above do not apply, then a rule violation is reported as TSLint assumes that a hook is used inside a regular function, which is not allowed.

Both screenshots contain functions that look like custom hooks, as they are composed of other hooks and do not render anything. If you name them as custom hooks are suggested to be named (e.g. `useLastBordereaus`). For more information on building custom hooks, take a look at [the hooks documentation](https://reactjs.org/docs/hooks-custom.html#extracting-a-custom-hook).

This TSLint rule closely matches the logic that the ESLint rule from the React team enforces:
https://reactjs.org/docs/hooks-faq.html#what-exactly-do-the-lint-rules-enforce

Let me know if you have any other questions :slightly_smiling_face:

**Comment by BenevidesLecontes** [comment]
@Gelio thank you for your support. Everything is clear now.

**Comment by BenevidesLecontes** [comment]
@Gelio now I'm having problem using these custom hooks.
<img width="1440" alt="Screen Shot 2019-04-26 at 12 41 06" src="https://user-images.githubusercontent.com/1839361/56819698-ab147e80-6820-11e9-820a-1c0003628d87.png">

**Comment by Gelio** [comment]
Your component is named `dashboard` - starts with a lowercase letter :slightly_smiling_face: To follow the convention, please use `Dashboard` :slightly_smiling_face:

**Comment by BenevidesLecontes** [comment]
@Gelio I saw that in the last minute that I reopened the issue, that's why i closed the issue and deleted the message.   🙂

**Comment by Gelio** [comment]
No worries :slightly_smiling_face: I did not notice you removed the comment before posting mine
